[package]
name = "rustic"
version = "0.1.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
derive_more = "0.99"
derive-getters = "0.2"
aes256ctr_poly1305aes = { path = "../aes256ctr_poly1305aes" } 
base64 = "0.13"
scrypt = { version = "0.8", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-aux = "3"
hex = { version = "0.4", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
# index
boomphf = "0.5"
# chunker
cdc = "0.1"
# local backend
walkdir = "2"
# commands
clap = { version = "3", features = ["derive"] }
prettytable-rs = "0.8"
itertools = "0.10"
