[package]
name = "rustic"
version = "0.1.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# macros
anyhow = "1.0"
ambassador = "0.2"
thiserror = "1.0"
derive_more = "0.99"
derive-getters = "0.2"
lazy_static = "1.4"
#crypto
aes256ctr_poly1305aes = { path = "../aes256ctr_poly1305aes" } 
sha2 = "0.10"
rand = "0.8"
scrypt = { version = "0.9", default-features = false }
# chunker
cdc = "0.1"
# serialization
base64 = "0.13"
binrw = "0.8"
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-aux = "3"
# other dependencies
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3"
# index
boomphf = {version = "0.5", optional = true}
# local backend
walkdir = "2"
ignore = "0.4"
# commands
gethostname = "0.2"
users = "0.11"
bytesize = "1"
clap = { version = "3", features = ["derive"] }
rpassword = "5"
prettytable-rs = {version = "0.8", default-features = false }
itertools = "0.10"
path-absolutize = "3"

# usefule crates:
# delegate -> impl methods from struct/enum element(s)

